FROM node:20-slim

WORKDIR /app

COPY package*.json ./

RUN npm config set fetch-retry-maxtimeout 120000 && \
    npm config set registry https://registry.npmmirror.com
    
RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]